services:
  backend:
    container_name: backend-devops-course
    image: backend-devops-course:latest
    build:
      context: ../
      dockerfile: docker/backend/Dockerfile
    restart: always
    volumes:
      - ../backend:/var/www/backend
    ports:
      - "8081:8080"
    environment:
      - REDIS_ENDPOINT=devops-course-cache-smallest-0xkflf.serverless.eun1.cache.amazonaws.com
      - REDIS_PORT=6379
      - DB_ENDPOINT=devops-course-database.cz488m2s6uzs.eu-north-1.rds.amazonaws.com
      - DB_PORT=5432
      - DB_NAME=db
      - DB_PASS=ZMIj8GYc92xoDWQ1khP3
      - DB_USER=postgres
  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=devops
      - POSTGRES_DB=devops
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
