apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  type: NodePort         # <-- додаємо
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8080
      nodePort: 30081    # порт, по якому можна стукати ззовні (30000-32767)
  selector:
    io.kompose.service: backend
status:
  loadBalancer: {}
