apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - command:
            - sh
            - /usr/local/bin/entrypoint.sh
          env:
            - name: REACT_APP_BACKEND_URL
              value: http://localhost:8080
          image: frontend-devops-course:latest
          name: frontend-devops-course
          ports:
            - containerPort: 3000
          resources: {}
          volumeMounts:
            - mountPath: /var/www/frontend
              name: frontend-claim0
      restartPolicy: Always
      volumes:
        - name: frontend-claim0
          persistentVolumeClaim:
            claimName: frontend-claim0
status: {}
