replicaCount: 1

image:
  repository: vitaliitarnavskyi/frontend-devops-course
  tag: "latest"
  pullPolicy: IfNotPresent

containerPort: 80

service:
  type: NodePort
  port: 80
  targetPort: 3000      # set to 3000 if your app listens there
  nodePort: 30080     # optional fixed port

env:
  API_BASE: "http://devops-course-backend:8081"

resources: {}

ingress:
  enabled: false
  className: ""
  hosts: []
  tls: []
